{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dakshata",
    "module": "at-api",
    "version": "1.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dakshata",
          "module": "public-library",
          "version": {
            "requires": "1.8.6"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-java",
          "version": {
            "requires": "3.13.10"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-objectmapper-jackson",
          "version": {
            "requires": "3.4.01"
          }
        }
      ],
      "files": [
        {
          "name": "at-api-1.8.6.jar",
          "url": "at-api-1.8.6.jar",
          "size": 30804,
          "sha512": "9c2a18ef6ec8a71495f63e83b35a8f331a9e4a23e24d0dc266c941dfe1d333a8065c08e28bc09708520b2f8a468255c6b3ff19d803005f4f59a8c48e176ed8e9",
          "sha256": "f640618cdcf3854c8d8dfcdcb1d09bf48bb5b85a2b51242fd029054ddbb8500f",
          "sha1": "10e2445fe6dace62f13be5eb869f366701833039",
          "md5": "55ac2b43895bc0417966fbed2da4cfb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dakshata",
          "module": "public-library",
          "version": {
            "requires": "1.8.6"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-java",
          "version": {
            "requires": "3.13.10"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-objectmapper-jackson",
          "version": {
            "requires": "3.4.01"
          }
        }
      ],
      "files": [
        {
          "name": "at-api-1.8.6.jar",
          "url": "at-api-1.8.6.jar",
          "size": 30804,
          "sha512": "9c2a18ef6ec8a71495f63e83b35a8f331a9e4a23e24d0dc266c941dfe1d333a8065c08e28bc09708520b2f8a468255c6b3ff19d803005f4f59a8c48e176ed8e9",
          "sha256": "f640618cdcf3854c8d8dfcdcb1d09bf48bb5b85a2b51242fd029054ddbb8500f",
          "sha1": "10e2445fe6dace62f13be5eb869f366701833039",
          "md5": "55ac2b43895bc0417966fbed2da4cfb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "at-api-1.8.6-sources.jar",
          "url": "at-api-1.8.6-sources.jar",
          "size": 11004,
          "sha512": "181045ff404e2090de63c4083368fa10443972e42f4758a60c3376c57e3c5c85ebcc00d4ab95ec2d80a66148c1d77e7d444fa75401fdcc365435b780eac683c0",
          "sha256": "beffe590ac02772c66a84d63e237dbdf17d07971e1d5641b5faafe929fb54b50",
          "sha1": "859164ff296f458fc8b9c6f19ea9f93a0afce437",
          "md5": "320957f6e6ed9e7d6bad131766214ea3"
        }
      ]
    }
  ]
}
