{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dakshata",
    "module": "public-library",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jasypt",
          "module": "jasypt",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.10"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "public-library-1.6.2.jar",
          "url": "public-library-1.6.2.jar",
          "size": 246207,
          "sha512": "93af8d95b9fe2e72613028eba3539903a091202f41872c6cc6aa6301db2a2305d6eca3a69344c5afdec1ffde0267d56d99429c12c1ab2043344bdf781bd758da",
          "sha256": "07c1e2346afdae86295a8eadb4be62a7503496f15c5c71fc174c0da4ddf9af27",
          "sha1": "6792ce1d2b53fb79348b557405c5ab6224dd5e63",
          "md5": "9478d2b0460d3d223fb229ef99fb5cf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jasypt",
          "module": "jasypt",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.10"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "public-library-1.6.2.jar",
          "url": "public-library-1.6.2.jar",
          "size": 246207,
          "sha512": "93af8d95b9fe2e72613028eba3539903a091202f41872c6cc6aa6301db2a2305d6eca3a69344c5afdec1ffde0267d56d99429c12c1ab2043344bdf781bd758da",
          "sha256": "07c1e2346afdae86295a8eadb4be62a7503496f15c5c71fc174c0da4ddf9af27",
          "sha1": "6792ce1d2b53fb79348b557405c5ab6224dd5e63",
          "md5": "9478d2b0460d3d223fb229ef99fb5cf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "public-library-1.6.2-sources.jar",
          "url": "public-library-1.6.2-sources.jar",
          "size": 97033,
          "sha512": "4295e233541ed6baa257a6bdd8a3bef15f28a59160df1f11cccd0884f371e56dbc44eed32bbafe17396c775b4ee1f61255b384835364b5716d34fafa011a70c0",
          "sha256": "4e09a8bb326078b9ba3aea5b3d0ae4710b5a0a74207c7d86634f93bb16220d23",
          "sha1": "b2c44357d368aff1537e0e9d3254b79ed1e30ef6",
          "md5": "7250e1f4ea0efcafe8674b08c3c1da3f"
        }
      ]
    }
  ]
}
