{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dakshata",
    "module": "at-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dakshata",
          "module": "public-library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-java",
          "version": {
            "requires": "3.9.00"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-objectmapper-jackson",
          "version": {
            "requires": "3.4.01"
          }
        }
      ],
      "files": [
        {
          "name": "at-api-1.0.0.jar",
          "url": "at-api-1.0.0.jar",
          "size": 22384,
          "sha512": "da796547e69199f38e3135d097d4ac8f8776b7973f6c4de95494c98373e0e0b7c5e314b51c978ce979e841167300f3509ebaf6fa328f80e7574549c05225c743",
          "sha256": "9d87a6f2723c1c6ed4fdc81097525b6a309ae6ff05b9618c0e80dc40e4f1731b",
          "sha1": "ff3b5069c435efed109ccb365bca034b62be0432",
          "md5": "272215082c9c58c843262c2fa1c78091"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dakshata",
          "module": "public-library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-java",
          "version": {
            "requires": "3.9.00"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-objectmapper-jackson",
          "version": {
            "requires": "3.4.01"
          }
        }
      ],
      "files": [
        {
          "name": "at-api-1.0.0.jar",
          "url": "at-api-1.0.0.jar",
          "size": 22384,
          "sha512": "da796547e69199f38e3135d097d4ac8f8776b7973f6c4de95494c98373e0e0b7c5e314b51c978ce979e841167300f3509ebaf6fa328f80e7574549c05225c743",
          "sha256": "9d87a6f2723c1c6ed4fdc81097525b6a309ae6ff05b9618c0e80dc40e4f1731b",
          "sha1": "ff3b5069c435efed109ccb365bca034b62be0432",
          "md5": "272215082c9c58c843262c2fa1c78091"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "at-api-1.0.0-sources.jar",
          "url": "at-api-1.0.0-sources.jar",
          "size": 9462,
          "sha512": "93155d0ea5e3cc29eed3346a4151a4b6a6921968003ae370be731c06aecfabe0b34eeffbc9d85e3c5a387607ccbb97d78c8dbda690c124146708318bbf618a40",
          "sha256": "71d7d5ca4d32cf1d47b25d13166f46de979e03a0cda1123b4828a5ae379d86a6",
          "sha1": "5197f0e4779238af3a884742203fe84538b56d20",
          "md5": "718bbeb20be64af008494eb88967a217"
        }
      ]
    }
  ]
}
