{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dakshata",
    "module": "at-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dakshata",
          "module": "public-library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-java",
          "version": {
            "requires": "3.13.10"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-objectmapper-jackson",
          "version": {
            "requires": "3.4.01"
          }
        }
      ],
      "files": [
        {
          "name": "at-api-1.0.0.jar",
          "url": "at-api-1.0.0.jar",
          "size": 31204,
          "sha512": "bfcefd6e963bd802f2e23cc83e40b6fc704b225cd0a1e661b87759b77004d7eb76124c7e48afa6f3654e6a13b1c8d563c59ccc8f5dd8e2046dd1c22bbc4176bd",
          "sha256": "4ec1c331a7df06fba9dc8d4853bf26429c57e920fdf29e85c6c198e94631a2a6",
          "sha1": "0e6d2eb9db63ed9267642cdb731a407e8bd28ef8",
          "md5": "9cf9c119711dba8c4239e8c380402bfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dakshata",
          "module": "public-library",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-java",
          "version": {
            "requires": "3.13.10"
          }
        },
        {
          "group": "com.konghq",
          "module": "unirest-objectmapper-jackson",
          "version": {
            "requires": "3.4.01"
          }
        }
      ],
      "files": [
        {
          "name": "at-api-1.0.0.jar",
          "url": "at-api-1.0.0.jar",
          "size": 31204,
          "sha512": "bfcefd6e963bd802f2e23cc83e40b6fc704b225cd0a1e661b87759b77004d7eb76124c7e48afa6f3654e6a13b1c8d563c59ccc8f5dd8e2046dd1c22bbc4176bd",
          "sha256": "4ec1c331a7df06fba9dc8d4853bf26429c57e920fdf29e85c6c198e94631a2a6",
          "sha1": "0e6d2eb9db63ed9267642cdb731a407e8bd28ef8",
          "md5": "9cf9c119711dba8c4239e8c380402bfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "at-api-1.0.0-sources.jar",
          "url": "at-api-1.0.0-sources.jar",
          "size": 11061,
          "sha512": "9c58508cfa3bab49be976d1597947ced6393e8c62baf04cfa2e8a8ed52c4f0892efe5ee4e4c6d68b2ac4765415f3efd1ef82f2928c38e145c1e603b00fd71da7",
          "sha256": "9037046fb8abaf77288ef33a21e5c8e538f24b3af3a470e3b75b209ca4a000a0",
          "sha1": "45a5bae5e60c2791d8ec015ea51358559a05e0ec",
          "md5": "6b5f844b033c0556a7b439a3f53ffb13"
        }
      ]
    }
  ]
}
