{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dakshata",
    "module": "public-library",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jasypt",
          "module": "jasypt",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.30"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "public-library-2.1.0.jar",
          "url": "public-library-2.1.0.jar",
          "size": 276896,
          "sha512": "f712d106d3c99816063e696411167aca70032e2ce66662717f4925f442064467b71db2e88e4bd57198cb32238cb37b76f94bb31ad862bc38d187b68e6ae51b1b",
          "sha256": "39cfbc16d2485f9fafe8e147a5b86648c391dbce162fa8b190ec23971f4f66b7",
          "sha1": "b8bb50b02a6db8829dfdeef3ec020123be149af6",
          "md5": "27b544f7a61733f8eafe4410087408bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jasypt",
          "module": "jasypt",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.30"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "public-library-2.1.0.jar",
          "url": "public-library-2.1.0.jar",
          "size": 276896,
          "sha512": "f712d106d3c99816063e696411167aca70032e2ce66662717f4925f442064467b71db2e88e4bd57198cb32238cb37b76f94bb31ad862bc38d187b68e6ae51b1b",
          "sha256": "39cfbc16d2485f9fafe8e147a5b86648c391dbce162fa8b190ec23971f4f66b7",
          "sha1": "b8bb50b02a6db8829dfdeef3ec020123be149af6",
          "md5": "27b544f7a61733f8eafe4410087408bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "public-library-2.1.0-sources.jar",
          "url": "public-library-2.1.0-sources.jar",
          "size": 105910,
          "sha512": "ead85cf7c4acbea4d115b8bcc619d0285c2fb8db0379aa3ae35b31c47281f0ac638b8bea8ae7ccd5623f2d50c416d0cf1e2631a7796f4a09ab1181f2abd8526e",
          "sha256": "64695e823af18e19a9518b89cbc00db40cb555a9e90b68b5d71ceed33511358a",
          "sha1": "0c7aef67013d76fc183d4668ab02bc3dfa2be81d",
          "md5": "d3566a2798744de9abc5f4161ae1235f"
        }
      ]
    }
  ]
}
